describe('普通融资流程',function(){
    it('normal',function(){
        cy.companylogin('9151010066759023X5','17708030002','admin@123')
        cy.get('.noleftborder___3tRe2 > p').click()
        cy.wait(3000)
        cy.get('.ant-input').type('澳新无贷前')
        cy.get('.ant-input-group-addon > .ant-btn').click()
        cy.wait(2000)
        cy.xpath('/html/body/div/section/main/div[2]/div[2]/div/div[2]/div/div/div[2]/div/div[1]/div/ul/li/div[3]/div[8]/a')
            .should('have.attr', 'target', '_blank')
            .should('have.attr', 'href', '/cui/financing/productDetail?id=3251')
        cy.visit('http://192.168.10.112/cui/financing/productDetail?id=3251')
        cy.get('#agree').click()
        cy.get('[style="text-align: center; margin-bottom: 40px;"] > .ant-btn').click()
        cy.get('#expectedAmount').type('123')
        cy.get('.ant-modal-footer > div > .ant-btn-primary').click()
        cy.url().should('eql','http://192.168.10.112/cui/success/apply')
        // cy.get('.ant-dropdown-trigger').trigger('mouseover')
        // cy.get(':nth-child(4) > a > :nth-child(2)').click()

    })
    it.only('normal_institution',function(){
        cy.banklogin('qxb_scs_admin','admin@123')
        cy.get(':nth-child(6) > .ant-menu-submenu-title').click()
        // cy.get(':nth-child(4) > a').click()
        // cy.get('#applicantName').type('成都育碧电脑软件有限公司')
        // cy.get('.ant-row-flex > :nth-child(1) > .ant-btn').click()
        // cy.wait(3000)
        // cy.get('span > a').click()
        // cy.get('.ant-cascader-picker > .ant-input').click()
        // cy.get('.ant-cascader-menu-item').click()
        // cy.get('[title="qxb_scs_admin（崔**）"]').click()
        // cy.get('.ant-modal-footer > div > .ant-btn-primary').click()

        cy.get(':nth-child(7) > a').click()
        // cy.get('#applicantName').type('成都育碧电脑软件有限公司')
        // cy.get('[style="margin-left: -8px; margin-right: -8px;"] > .ant-col-24 > .ant-row-flex > :nth-child(1) > .ant-btn').click()
        // cy.wait(3000)
        // cy.get(':nth-child(9) > :nth-child(3)').click()
        cy.get('.ant-tabs-nav > :nth-child(1) > :nth-child(2)').click()
        cy.wait(3000)
        cy.get('.ant-tabs-tabpane-active > [style="margin-left: -8px; margin-right: -8px;"] > :nth-child(2) > .ant-row > .ant-form-item-control-wrapper > .ant-form-item-control > .ant-form-item-children > .ant-input-affix-wrapper > #applicantName').type('成都育碧电脑软件有限公司')
        cy.get('.ant-tabs-tabpane-active > [style="margin-left: -8px; margin-right: -8px;"] > .ant-col-24 > .ant-row-flex > :nth-child(1) > .ant-btn').click()
        cy.wait(3000)
        cy.get(':nth-child(3) > .ant-table-wrapper > .ant-spin-nested-loading > .ant-spin-container > .ant-table > .ant-table-content > .ant-table-body > table > .ant-table-tbody > .ant-table-row > :nth-child(9) > :nth-child(5) > span > a').click()

    })
})