describe('互联网端信用查询',function(){
    it('ui',function(){
        cy.userlogin('17708030000','admin@123')
        cy.wait(3000)   
        cy.get(':nth-child(2) > .ant-menu-submenu-title > span').trigger('mouseover')
        cy.get(':nth-child(9) > .menu_item___2UpIk').click()
        cy.wait(3000)
        cy.get('.ant-menu > :nth-child(14) > a').click()
        cy.get('.ant-input').type('腾讯科技')
        cy.get('.ant-col > .ant-btn').click()
        cy.get('[text="腾讯科技（成都）有限公司"]').click()
        cy.wait(3000)
        cy.contains('基本信息')
        cy.contains('经营状况')
        cy.contains('经营风险')
        cy.get('[style="width: 1200px; margin: auto;"] > :nth-child(1) > .ant-tabs-nav-container > .ant-tabs-nav-wrap > .ant-tabs-nav-scroll > .ant-tabs-nav > :nth-child(1) > :nth-child(3)').click()
        cy.contains('奚丹')
        cy.contains('22000万美元')
        cy.contains('贵安新区腾讯数码有限公司')
        cy.contains('中霸集团有限公司')
        cy.contains('Charles St leger Searle')
        cy.contains('马化腾')
        cy.contains('章程修正案备案')
    })
})